### PR TITLE
Made changes to fix the issue.

### LINKED ISSUE #1: no member function named "add" for std::map
Please check this line, there is no member function named add for std::map data. 

https://github.com/shamim-akhtar/fsm-cpp/blob/15a533b9589c804c7be37249841b1f319b386335/include/FiniteStateMachine.h#L109

### PR DESCRIPTION
**Pull request by shamim-akhtar**

### CODE REVIEW

File: examples/example_turnstile/main.cpp [hunk 1]
```diff
@@ -13,23 +14,47 @@ enum class TurnstileStateType
...
+template <typename T> class Func : public State<T>::Functor
+{
+  std::string _name;
+public:
+  explicit Func(std::string name)
+    : _name(name)
+  {
+
+  }
+  void operator()(State<T>& state) override
```
Comment (Lecrapouille) [inline examples/example_turnstile/main.cpp]: virtual void operator()(State<T>& state) override

File: examples/example_turnstile/main.cpp [hunk 2]
```diff
@@ -13,23 +14,47 @@ enum class TurnstileStateType
...
+      new Func<TurnstileStateType>("OnExit"),
+      new Func<TurnstileStateType>("OnUpdate")
+      )
     , mFsm(fsm)
   {
   }
 
   void enter()
   {
+    State<TurnstileStateType>::enter();
```
Comment (Lecrapouille) [inline examples/example_turnstile/main.cpp:49]: virtual void enter() override

File: examples/example_turnstile/main.cpp [hunk 3]
```diff
@@ -13,23 +14,47 @@ enum class TurnstileStateType
...
     printf("Turnstile state: LOCKED\n");
   }
 
   void update()
   {
+    State<TurnstileStateType>::update();
```
Comment (Lecrapouille) [inline examples/example_turnstile/main.cpp:55]: virtual void update() override

File: examples/example_turnstile/main.cpp [hunk 4]
```diff
@@ -54,11 +79,13 @@ class TurnstileUnLockedState : public State<TurnstileStateType>
 
   void enter()
   {
+    State<TurnstileStateType>::enter();
```
Comment (Lecrapouille) [inline examples/example_turnstile/main.cpp:78]: virtual ... override

File: examples/example_turnstile/main.cpp [hunk 5]
```diff
@@ -54,11 +79,13 @@ class TurnstileUnLockedState : public State<TurnstileStateType>
...
     printf("Turnstile state: UNLOCKED\n");
   }
 
   void update()
   {
+    State<TurnstileStateType>::update();
```
Comment (Lecrapouille) [inline examples/example_turnstile/main.cpp:84]: virtual ... override

File: include/FiniteStateMachine.h [hunk 6]
```diff
@@ -99,32 +101,49 @@ namespace Patterns
...
         return;
-      mStates[state->getID()] = state;
+      add(state->getID(), state);
+      //mStates[state->getID()] = state;
     }
 
     void add(T stateID, State<T>* state)
     {
-      mStates.add(stateID, state);
+      if (mStates.find(stateID) == mStates.end())
```
Comment (Lecrapouille) [inline include/FiniteStateMachine.h]: void add(T stateID, State<T>* state)
{
  assert(mStates.find(stateID) == mStates.end() && "Invalid State ID");
  mStates.insert(std::make_pair(stateID, state));
}

or instead of assert return true/false;

File: include/FiniteStateMachine.h [hunk 7]
```diff
@@ -99,32 +101,49 @@ namespace Patterns
...
+        assert(0);
+      }
     }
 
     State<T>* getState(T stateID)
     {
-      return mStates[stateID];
+      if (mStates.find(stateID) != mStates.end())
+        return mStates[stateID];
+      return nullptr;
```
Comment (Lecrapouille) [inline include/FiniteStateMachine.h]: Possible alternative:
State<T>* getState(T stateID)
{
   assert(mStates.find(stateID) != mStates.end() && "Invalid state ID");
   return mStates[stateID];
}
